# Generated by Django 4.2.6 on 2024-04-12 19:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('documento', models.IntegerField(unique=True, validators=[django.core.validators.MinValueValidator(3400000, 'Digite un numero de documento valido'), django.core.validators.MaxValueValidator(1999999999, 'Digite un numero de documento valido')], verbose_name='Numero de documento')),
                ('celular', models.PositiveIntegerField(unique=True, validators=[django.core.validators.MinValueValidator(3000000000, 'Digite un numero de telefono valido'), django.core.validators.MaxValueValidator(3599999999, 'Digite un numero de telefono valido')])),
                ('email', models.EmailField(db_column='correo', max_length=100, unique=True, validators=[django.core.validators.EmailValidator()])),
                ('password', models.CharField(blank=True, max_length=255, null=True)),
                ('imagen', models.ImageField(blank=True, db_column='imagen', null=True, upload_to='imagen_usuario')),
                ('registro', models.DateField(auto_now_add=True)),
                ('last_login', models.DateTimeField(auto_now=True, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'usuario',
                'ordering': ['-id'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Alimentacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('gr_gallina_dia', models.CharField(db_column='Gr/Gallina/Dia', max_length=10)),
                ('kg_total', models.CharField(max_length=10)),
                ('bultos_total', models.CharField(max_length=10)),
                ('c_a', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'alimentacion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('documento', models.IntegerField()),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ficha',
            fields=[
                ('id_ficha', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_regis', models.DateField(auto_now_add=True)),
                ('num_ficha', models.CharField(max_length=50)),
                ('estado_ficha', models.IntegerField()),
            ],
            options={
                'db_table': 'ficha',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Gallinas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_ingreso', models.DateField(auto_now_add=True)),
                ('cantidad_gallinas', models.PositiveIntegerField()),
                ('peso_promedio', models.PositiveIntegerField()),
                ('edad_sem', models.PositiveIntegerField()),
                ('procedencia', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Gallina',
                'verbose_name_plural': 'Gallinas',
                'db_table': 'gallinas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Galpones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('nombre_galpon', models.CharField(max_length=100, unique=True)),
                ('ancho', models.IntegerField(validators=[django.core.validators.MinValueValidator(1, message='El número debe ser mayor o igual a 0.'), django.core.validators.MaxValueValidator(900, message='El número debe ser menor o igual a 900.'), django.core.validators.RegexValidator('^\\d+$', 'Ingrese un número entero válido sin comas, puntos ni signos.')])),
                ('largo', models.IntegerField(validators=[django.core.validators.MinValueValidator(1, message='El número debe ser mayor o igual a 0.'), django.core.validators.MaxValueValidator(900, message='El número debe ser menor o igual a 900.'), django.core.validators.RegexValidator('^\\d+$', 'Ingrese un número entero válido sin comas, puntos ni signos.')])),
                ('area', models.IntegerField()),
                ('capac_bebed', models.IntegerField()),
                ('cant_bebed', models.IntegerField(validators=[django.core.validators.MinValueValidator(1, message='El número debe ser mayor o igual a 0.'), django.core.validators.MaxValueValidator(900, message='El número debe ser menor o igual a 900.'), django.core.validators.RegexValidator('^\\d+$', 'Ingrese un número entero válido sin comas, puntos ni signos.')])),
                ('capac_comed', models.IntegerField()),
                ('cant_comed', models.IntegerField(validators=[django.core.validators.MinValueValidator(1, message='El número debe ser mayor o igual a 0.'), django.core.validators.MaxValueValidator(900, message='El número debe ser menor o igual a 900.'), django.core.validators.RegexValidator('^\\d+$', 'Ingrese un número entero válido sin comas, puntos ni signos.')])),
                ('capac_gall', models.IntegerField()),
                ('cant_gall', models.IntegerField(validators=[django.core.validators.MinValueValidator(1, message='El número debe ser mayor o igual a 0.'), django.core.validators.MaxValueValidator(900, message='El número debe ser menor o igual a 900.'), django.core.validators.RegexValidator('^\\d+$', 'Ingrese un número entero válido sin comas, puntos ni signos.')])),
                ('capac_nidales', models.IntegerField()),
                ('cant_nidales', models.IntegerField(validators=[django.core.validators.MinValueValidator(1, message='El número debe ser mayor o igual a 0.'), django.core.validators.MaxValueValidator(900, message='El número debe ser menor o igual a 900.'), django.core.validators.RegexValidator('^\\d+$', 'Ingrese un número entero válido sin comas, puntos ni signos.')])),
            ],
            options={
                'db_table': 'galpones',
                'ordering': ['-id'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Jornada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jornada', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'jornada',
                'ordering': ['id'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Linea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'linea',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MortalidadDescarte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('cant_muertas', models.IntegerField()),
                ('cant_descarte', models.IntegerField()),
                ('saldo', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'mortalidad_descarte',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Nombreficha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'nombreficha',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProduccionDiaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('rotos', models.IntegerField()),
                ('descarte', models.IntegerField()),
                ('fecha', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'produccion_diaria',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Registrodiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'registrodiario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_rol', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'rol',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoAlimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'tipo_alimento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoDescarte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'tipo_descarte',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoDoc',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('tipo_doc', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'tipo_doc',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TiposHuevos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipos_huevos', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'tipos_huevos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Vacunas',
            fields=[
                ('idvacunas', models.AutoField(db_column='Idvacunas', primary_key=True, serialize=False)),
                ('nombrev', models.CharField(db_column='Nombrev', max_length=60)),
                ('presentacion', models.CharField(db_column='Presentacion', max_length=60)),
            ],
            options={
                'db_table': 'vacunas',
                'managed': False,
            },
        ),
    ]
