# Generated by Django 4.1.6 on 2023-06-01 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0007_tipoalimento'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoDescarte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'tipo_descarte',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Vacunas',
            fields=[
                ('idvacunas', models.AutoField(db_column='Idvacunas', primary_key=True, serialize=False)),
                ('nombrev', models.CharField(db_column='Nombrev', max_length=60)),
                ('presentacion', models.CharField(db_column='Presentacion', max_length=60)),
            ],
            options={
                'db_table': 'vacunas',
                'managed': False,
            },
        ),
    ]
