# Generated by Django 4.2.6 on 2024-03-03 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0008_tipodescarte_vacunas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nombreficha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'nombreficha',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Registrodiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'registrodiario',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='DetalleJornada',
        ),
        migrations.DeleteModel(
            name='Estados',
        ),
        migrations.AlterModelOptions(
            name='galpones',
            options={'managed': False, 'ordering': ['-id']},
        ),
    ]
